#url: johannesklingebiel.de

# Comment url for local testing

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
  series:
    output: true
    permalink: /collections/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: portfolio

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate-content

# SASS Options
sass:
    sass_dir: _sass
