url: johannesklingebiel.de

# Comment url for local testing

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
  collections:
    output: true
    permalink: /collections/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: portfolio
