url: https://klingebeil.github.io
baseurl: "/homepage"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
  collections:
    output: true
    permalink: /collections/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: portfolio
