url: johannesklingebiel.de
# baseurl: "johannesklingebiel.de"

# Uncomment for local testing
# baseurl. "/homepage"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
  collections:
    output: true
    permalink: /collections/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: portfolio
