baseurl: ""
url: ""

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
  series:
    output: true
    permalink: /collections/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: portfolio

markdown: kramdown

plugins:
  - jekyll-feed

paginate_content:
  debug: true
  collections: pages, posts

# SASS Options
sass:
    sass_dir: _sass
